### ISSUE TITLE
build `jenkins-contribution-extractor` instead of `jenkins-stats`

### ISSUE THREAD

**Issue by jmMeessen** [jenkins-infra/jenkins-contribution-extractor#47]
### What feature do you want to see added?

With the move of the application to the `jenkins-infra` org, the repository application has also been renamed. For tidyness, this implies that the executable has to be rename.

```[tasklist]
### Tasks
- [x] Rename main file to jenkins-contribution-extractor
- [x] update make file
- [x] update goReleaser
- [x] test release process
- [x] test codecoverage
```

**Comment by jmMeessen** [comment]
While updating the GoReleaser configuration file, I have seen that the Brew tap update commit is configured as 

```
    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: jean-marc@meessen-web.org
```

Opinions about the automated commit user (IMHO this one is Ok) and the associated email? Is there a generic jenkins-infra email. @gounthar @lemeurherve 

Note that this hidden deep in the bowels of the system and is only of marginal importance.
